# Generated by Django 5.1.7 on 2025-06-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
