# Generated by Django 5.1.7 on 2025-06-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0002_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
    ]
