# Generated by Django 5.1.7 on 2025-06-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0003_partidopolitico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidopolitico',
            name='color',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='partidopolitico',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='partidopolitico',
            name='sigla',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
