# Generated by Django 5.1.7 on 2025-06-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0005_seccion_alter_partidopolitico_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='electoral.recinto')),
            ],
            options={
                'unique_together': {('numero', 'recinto')},
            },
        ),
    ]
