# Generated by Django 5.1.7 on 2025-06-29 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0006_mesaelectoral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Nacional'), ('MUNICIPAL', 'Municipal'), ('REGIONAL', 'Regional')], max_length=20)),
                ('fecha', models.DateField()),
                ('secciones', models.ManyToManyField(blank=True, to='electoral.seccion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mesaelectoral',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargo',
            name='eleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='electoral.eleccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesaelectoral',
            name='eleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='electoral.eleccion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mesaelectoral',
            unique_together={('numero', 'recinto', 'eleccion')},
        ),
    ]
