# Generated by Django 5.1.7 on 2025-07-06 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0007_alter_recinto_nombre_eleccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recinto',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recintos', to='electoral.seccion'),
        ),
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidaturas', models.ManyToManyField(to='electoral.candidatura')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electoral.cargo')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeletas', to='electoral.eleccion')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electoral.seccion')),
            ],
            options={
                'unique_together': {('eleccion', 'seccion', 'cargo')},
            },
        ),
    ]
