# Generated by Django 5.1.7 on 2025-07-06 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0008_eleccion_activa_recinto_seccion_papeleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacionVotanteEleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votante_id', models.UUIDField()),
                ('voto_emitido', models.BooleanField(default=False)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='electoral.eleccion')),
                ('recinto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electoral.recinto')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electoral.seccion')),
            ],
            options={
                'unique_together': {('votante_id', 'eleccion')},
            },
        ),
    ]
