# Generated by Django 5.1.7 on 2025-07-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0009_participacionvotanteeleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papeleta',
            name='candidaturas',
            field=models.ManyToManyField(related_name='papeletas', to='electoral.candidatura'),
        ),
    ]
