# Generated by Django 5.1.7 on 2025-07-07 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0010_alter_papeleta_candidaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacionvotanteeleccion',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='electoral.mesaelectoral'),
        ),
    ]
