# Generated by Django 5.1.7 on 2025-07-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0011_participacionvotanteeleccion_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacionvotanteeleccion',
            name='apellido_paterno',
            field=models.CharField(blank=True, help_text='Apellido paterno extraído', max_length=100),
        ),
        migrations.AddField(
            model_name='participacionvotanteeleccion',
            name='nombre_completo',
            field=models.CharField(blank=True, help_text='Nombre completo del votante', max_length=200),
        ),
    ]
