# Generated by Django 5.1.7 on 2025-07-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0012_participacionvotanteeleccion_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuradoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante_id', models.UUIDField(help_text='UUID de ParticipacionVotanteEleccion.votante_id')),
                ('user4_id', models.IntegerField(help_text='ID del CustomUser creado en Sistema 4')),
                ('username', models.CharField(max_length=150)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='electoral.mesaelectoral')),
            ],
            options={
                'verbose_name': 'Asignación Jurado–Mesa',
                'verbose_name_plural': 'Asignaciones Jurado–Mesa',
                'unique_together': {('participante_id', 'mesa')},
            },
        ),
    ]
