# Generated by Django 5.1.7 on 2025-07-11 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0013_juradomesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juradomesa',
            name='participante_id',
            field=models.ForeignKey(db_column='participante_id', on_delete=django.db.models.deletion.CASCADE, to='electoral.participacionvotanteeleccion', to_field='votante_id'),
        ),
        migrations.AlterField(
            model_name='participacionvotanteeleccion',
            name='votante_id',
            field=models.UUIDField(unique=True),
        ),
    ]
