# Generated by Django 5.1.7 on 2025-07-10 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('votante_id', models.UUIDField()),
                ('mesa_id', models.IntegerField()),
                ('habilitada', models.BooleanField(default=False)),
                ('habilitada_por', models.IntegerField(null=True)),
                ('habilitada_en', models.DateTimeField(null=True)),
                ('votada_en', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatura_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('papeleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='votacion.papeleta')),
            ],
        ),
    ]
